runtime: python39
entrypoint: gunicorn -b :8080 app:app --timeout 300

automatic_scaling:
  max_instances: 3
  min_instances: 1

env_variables:
  GCP_PROJECT_ID: "youtube-full-automated"
  GCP_REGION: "us-central1"

runtime: custom
env: flex
service: default

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# 무료 한도 유지를 위한 자동 확장 설정
automatic_scaling:
  min_instances: 0  # 트래픽 없을 때 0으로 줄이기
  max_instances: 1  # 무료 한도 내 유지
