runtime: python39
entrypoint: gunicorn -b :8080 app:app --timeout 300

automatic_scaling:
  max_instances: 3
  min_instances: 1

env_variables:
  GCP_PROJECT_ID: "youtube-full-automated"
  GCP_REGION: "us-central1"
