runtime: custom
env: flex
service: default

runtime_config:
  python_version: 3.9

manual_scaling:
  instances: 1  # 비용 절감을 위해 고정된 인스턴스 1개 사용

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

env_variables:
  GCP_PROJECT_ID: "youtube-full-automated"
  GCP_REGION: "us-central1"
