steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'us-central1-docker.pkg.dev/$PROJECT_ID/youtube-auto-upload/youtube-auto-upload:$COMMIT_SHA',
    '--build-arg', 'YOUTUBE_CLIENT_ID=$_YOUTUBE_CLIENT_ID',
    '--build-arg', 'YOUTUBE_CLIENT_SECRET=$_YOUTUBE_CLIENT_SECRET',
    '--build-arg', 'YOUTUBE_REFRESH_TOKEN=$_YOUTUBE_REFRESH_TOKEN',
    '--build-arg', 'OPENAI_API_KEYS=$_OPENAI_API_KEYS',
    '--build-arg', 'GCP_SERVICE_ACCOUNT_KEY=$_GCP_SERVICE_ACCOUNT_KEY',
    '.'
  ]
  env: ['DOCKER_BUILDKIT=1']
  timeout: 1800s

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'us-central1-docker.pkg.dev/$PROJECT_ID/youtube-auto-upload/youtube-auto-upload:$COMMIT_SHA'
  ]
  timeout: 1200s

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud auth activate-service-account --key-file=/workspace/gcp_key.json
      gcloud run deploy youtube-auto-upload \
        --image=us-central1-docker.pkg.dev/$PROJECT_ID/youtube-auto-upload/youtube-auto-upload:$COMMIT_SHA \
        --region=us-central1 \
        --platform=managed \
        --allow-unauthenticated \
        --memory=2Gi \
        --timeout=900s \
        --port=8080 \
        --set-env-vars=YOUTUBE_CLIENT_ID=$_YOUTUBE_CLIENT_ID,YOUTUBE_CLIENT_SECRET=$_YOUTUBE_CLIENT_SECRET,YOUTUBE_REFRESH_TOKEN=$_YOUTUBE_REFRESH_TOKEN,OPENAI_API_KEYS=$_OPENAI_API_KEYS,GCP_SERVICE_ACCOUNT_KEY=$_GCP_SERVICE_ACCOUNT_KEY
  env:
    - 'CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE=/workspace/gcp_key.json'
  timeout: 600s

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 50
  substitution_option: 'ALLOW_LOOSE'

substitutions:
  _YOUTUBE_CLIENT_ID: ''
  _YOUTUBE_CLIENT_SECRET: ''
  _YOUTUBE_REFRESH_TOKEN: ''
  _OPENAI_API_KEYS: ''
  _GCP_SERVICE_ACCOUNT_KEY: ''
