steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_SERVICE_NAME}:latest', '.']
    id: 'build'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_SERVICE_NAME}:latest']
    id: 'push'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', '${_SERVICE_NAME}',
      '--image', '${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_SERVICE_NAME}:latest',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--min-instances=0',
      '--max-instances=1',
      '--cpu=1',
      '--memory=512Mi',
      '--set-env-vars', 'OPENAI_API_KEYS=${_OPENAI_API_KEYS}',
      '--set-env-vars', 'PEXELS_API_KEY=${_PEXELS_API_KEY}',
      '--set-env-vars', 'YOUTUBE_CLIENT_ID=${_YOUTUBE_CLIENT_ID}',
      '--set-env-vars', 'YOUTUBE_CLIENT_SECRET=${_YOUTUBE_CLIENT_SECRET}',
      '--set-env-vars', 'YOUTUBE_REFRESH_TOKEN=${_YOUTUBE_REFRESH_TOKEN}',
      '--set-env-vars', 'ELEVENLABS_API_KEY=${_ELEVENLABS_API_KEY}',
      '--set-env-vars', 'GEMINI_API_KEY=${_GEMINI_API_KEY}'
    ]
    id: 'deploy'
    secretEnv: ['_OPENAI_API_KEYS', '_PEXELS_API_KEY', '_YOUTUBE_CLIENT_ID', '_YOUTUBE_CLIENT_SECRET', '_YOUTUBE_REFRESH_TOKEN', '_ELEVENLABS_API_KEY', '_GEMINI_API_KEY']  # 이 부분 추가

options:
  machineType: 'E2_HIGHCPU_8'

substitutions:
  _ARTIFACT_REGISTRY: us-central1-docker.pkg.dev
  _SERVICE_NAME: gcp-youtube-automation
  _REGION: us-central1

availableSecrets:
  secretManager:
  - versionName: projects/youtube-fully-automated/secrets/OPENAI_API_KEYS/versions/latest
    env: '_OPENAI_API_KEYS'
  - versionName: projects/youtube-fully-automated/secrets/PEXELS_API_KEY/versions/latest
    env: '_PEXELS_API_KEY'
  - versionName: projects/youtube-fully-automated/secrets/YOUTUBE_CLIENT_ID/versions/latest
    env: '_YOUTUBE_CLIENT_ID'
  - versionName: projects/youtube-fully-automated/secrets/YOUTUBE_CLIENT_SECRET/versions/latest
    env: '_YOUTUBE_CLIENT_SECRET'
  - versionName: projects/youtube-fully-automated/secrets/YOUTUBE_REFRESH_TOKEN/versions/latest
    env: '_YOUTUBE_REFRESH_TOKEN'
  - versionName: projects/youtube-fully-automated/secrets/ELEVENLABS_API_KEY/versions/latest
    env: '_ELEVENLABS_API_KEY'
  - versionName: projects/youtube-fully-automated/secrets/GEMINI_API_KEY/versions/latest
    env: '_GEMINI_API_KEY'

images:
  - '${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_SERVICE_NAME}:latest'
