steps:
  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      '$_ARTIFACT_REGISTRY/$PROJECT_ID/$_SERVICE_NAME:latest',
      '.'
    ]
    id: 'build-docker-image'

  # Docker 이미지 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '$_ARTIFACT_REGISTRY/$PROJECT_ID/$_SERVICE_NAME:latest'
    ]
    id: 'push-docker-image'

  # Cloud Run에 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run',
      'deploy',
      '$_SERVICE_NAME',
      '--image',
      '$_ARTIFACT_REGISTRY/$PROJECT_ID/$_SERVICE_NAME:latest',
      '--region',
      '$_REGION',
      '--platform',
      'managed',
      '--allow-unauthenticated',
      '--set-env-vars',
      'OPENAI_API_KEYS=$_OPENAI_API_KEYS,PEXELS_API_KEY=$_PEXELS_API_KEY,YOUTUBE_CLIENT_ID=$_YOUTUBE_CLIENT_ID,YOUTUBE_CLIENT_SECRET=$_YOUTUBE_CLIENT_SECRET,YOUTUBE_REFRESH_TOKEN=$_YOUTUBE_REFRESH_TOKEN,ELEVENLABS_API_KEY=$_ELEVENLABS_API_KEY,GEMINI_API_KEY=$_GEMINI_API_KEY'
    ]
    id: 'deploy-to-cloud-run'

# 환경 변수 대체 (실제 값은 트리거에서 설정)
substitutions:
  _ARTIFACT_REGISTRY: us-central1-docker.pkg.dev
  _SERVICE_NAME: gcp-youtube-automation
  _REGION: us-central1

# 빌드 완료 후 이미지 저장
images:
  - '$_ARTIFACT_REGISTRY/$PROJECT_ID/$_SERVICE_NAME:latest'
