# src/tts_generator.py
import os
import logging
from elevenlabs import generate, play, set_api_key

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def generate_tts_audio(script: str, elevenlabs_api_key: str, elevenlabs_voice_id: str) -> str | None:
    """
    ElevenLabs API를 사용하여 스크립트를 오디오 파일로 변환합니다.
    """
    if not script:
        logging.error("No script provided for TTS generation.")
        return None
    if not elevenlabs_api_key or not elevenlabs_voice_id:
        logging.error("ElevenLabs API key or voice ID is missing.")
        return None

    try:
        set_api_key(elevenlabs_api_key)
        
        logging.info(f"Generating audio for script (first 50 chars): {script[:50]}...")

        # ElevenLabs API를 사용하여 오디오 생성
        audio = generate(
            text=script,
            voice=elevenlabs_voice_id,
            model="eleven_multilingual_v2" # 또는 "eleven_turbo_v2" 등 적절한 모델
        )

        output_audio_path = os.path.join(os.getcwd(), "generated_audio.mp3")
        with open(output_audio_path, "wb") as f:
            f.write(audio)
        
        logging.info(f"Audio generated and saved to {output_audio_path}")
        return output_audio_path
    except Exception as e:
        logging.error(f"Error generating TTS audio with ElevenLabs: {e}", exc_info=True)
        return None

if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO)
    test_script = "Hello, this is a test audio generated by ElevenLabs for your YouTube Shorts automation."
    test_elevenlabs_key = os.environ.get("ELEVENLABS_API_KEY")
    test_elevenlabs_voice = os.environ.get("ELEVENLABS_VOICE_ID")

    if not test_elevenlabs_key or not test_elevenlabs_voice:
        logging.error("ELEVENLABS_API_KEY or ELEVENLABS_VOICE_ID environment variable not set for local testing.")
        logging.info("Please set these variables to run local TTS test.")
    else:
        audio_file = generate_tts_audio(test_script, test_elevenlabs_key, test_elevenlabs_voice)
        if audio_file:
            print(f"Test audio saved: {audio_file}")
            # play(audio) # 로컬에서 오디오 재생 (Cloud Run에서는 작동 안 함)
        else:
            print("Failed to generate test audio.")
