name: Cleanup Artifact Registry

on:
  schedule:
    - cron: '0 12 * * *'  # 매일 UTC 기준 12시 (한국 시간 오후 9시)에 실행
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: 'projects/94662874801/locations/global/workloadIdentityPools/github-pool-v2/providers/github-provider'
        service_account: 'github-actions-sa@youtube-fully-automated.iam.gserviceaccount.com'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Run Cleanup Script
      run: |
        chmod +x cleanup-repo-fixed.sh
        ./cleanup-repo-fixed.sh
