name: Cleanup Old Workflow Runs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # 매주 일요일 UTC 00:00

jobs:
  delete-old-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete old workflow runs
        uses: peter-evans/delete-workflow-runs@v2
        with:
          keep_minimum_runs: 5
          days_old: 7
