name: Cleanup Old Workflow Runs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # 매주 일요일 UTC 00:00 (한국 시간 오전 9시)

jobs:
  delete-old-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: peter-evans/delete-old-workflow-runs@v3 # 또는 다른 cleanup 액션
        with:
          package-type: workflow_run # workflow run artifacts를 대상으로 지정
          keep_minimum_runs: 5 
          days_old: 7
