name: Build and Push Docker Image

on:
  push:
    branches: [ main ] # 또는 master, 개발 브랜치 등

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GCR
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        
    - name: Build and Push Docker Image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/youtube-automation .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/youtube-automation
